name: macOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5.x SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'   
      
      - name: Build Coyote samples
        run: ./Scripts/build-tests.ps1
        shell: pwsh
      
      - name: Test Coyote samples
        run: dotnet ./Common/bin/net5.0/TestDriver.dll
        shell: pwsh
