name: Build and Test CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      COYOTE_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.x SDK
        uses: actions/setup-dotnet@v1
      - name: Build Coyote samples
        run: ./Scripts/build-tests.ps1
        shell: pwsh
      - name: Test Coyote samples
        run: dotnet ./Common/bin/net6.0/TestDriver.dll
        shell: pwsh
